# Generated by Django 2.2.4 on 2019-08-06 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_backend', '0003_auto_20190806_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartinventory',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rest_backend.Cart'),
        ),
    ]
