# Generated by Django 2.2.4 on 2019-08-06 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_backend', '0004_auto_20190806_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartinventory',
            name='qty',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='orderinventory',
            name='qty',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
